### ISSUE TITLE
Holes too loose

### ISSUE THREAD

**Issue by viesturz** [Stealthchanger/Toolchanger#1]
Hey, I'm printing with quite spot-on dimensions, external perimenters first and the holes come out very loose.
The pins literally fall out and the bushings hold with minimal force.
The magnet holes are also quite oversized.

Also if you can update the instructions if they should be glued in place (recommended glue) or just press fitted.

**Comment by viesturz** [comment]
Nope, just straight send to print. 
I'm tuning my flow based on top layer, typically resulting in 0.94 for ASA. And printing with external perimeters first which gives pretty spot on to slightly undersized external dimensions.

My guess would be that external perimeters last should add about 0.1-0.2mm to each wall and would mostly resolve this. 

Some pics for reference. 

![PXL_20240109_064729421 MP](https://github.com/Hellsparks/StealthChanger/assets/1640947/f58c8f78-7a97-492b-b1f3-172c9dfa0dc7)
![PXL_20240109_064831519 MP](https://github.com/Hellsparks/StealthChanger/assets/1640947/8812a14e-1203-4f41-9d96-2b8da69bbc8e)

**Comment by TheSin-** [comment]
for ref I always print perim first, not for or against but this might be way I could never get lit working for me properly.

**Comment by TheSin-** [comment]
I've tuned my printer and I'm now seeing the same issues.

I'm working on figuring out the best approach since we can't really have users drilling/reaming parts cause there is no direct access.

**Comment by TheSin-** [comment]
This is fixed just not released yet.
