### ISSUE TITLE
Write a "Before you start" wiki section

### ISSUE THREAD

**Issue by TheSin-** [Stealthchanger/Toolchanger#27]
We need to add a things to consider before you start

- Frame 2040 vs top mounted docks vs frame buffer, pros and cons
- things to consider for canbus
- things to consider for cable management
- answer the you should have tap on every tool
- etc...

**Comment by TheSin-** [comment]
Maybe @BrewNinja can take this on?  Thoughts @BrewNinja ?

**Comment by BrewNinja** [comment]
Sure can!

**Comment by TheSin-** [comment]
Done in  https://github.com/Stealthchanger/Toolchanger/commit/eb3a9e1614d4aa0ad1b517eb68f17d1797640c4e
