### ISSUE TITLE
Old TAP pcb mounting offset not compatible with current shuttle offsets

### ISSUE THREAD

**Issue by kiwidave72** [Stealthchanger/Toolchanger#38]
I have both the new TAP PCB and old v5 PCB functionally they are fine.

Issue: that the old v5 PCB mounting holes make the PCB mount to low on the backplates (dragonburner, and possibly the others).
Results from the Issue: when docking the top of the TAP flag (if you can call it that) can catch on the PCB when moving into position.
When other tool heads are bring picked up. The Top belt of the XY gantry can catch on the PCB of the tool head with the PCB install.

Solution: Warning on manual that the old PCB's are not supported. and that the PCB must be flush with the backplate.
Change tool docking paths to move shuttle under the PCB when docking.

![image3 (3)](https://github.com/Stealthchanger/Toolchanger/assets/8468461/b0843650-7185-43a8-a4c6-948bf876a800)

![image4 (1)](https://github.com/Stealthchanger/Toolchanger/assets/8468461/9636b54a-22e7-4c6e-8799-bb0d3d4fa843)

**Comment by TheSin-** [comment]
Your board is upside down, turn it.

Also if you want to run it upside down just change you docking path.

v1 and v2 are fully compat I run both personally.
